name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inorbit
